version     = "0.1.0"
author      = "treeform"
description = "Low-poly 3D game engine for AI research."
license     = "MIT"

srcDir = "src"

requires "nim >= 2.2.10"
requires "https://github.com/treeform/bassy"
requires "https://github.com/treeform/fixxy"
requires "silky"
requires "windy"
requires "pixie"
requires "vmath"
requires "chroma"
requires "bumpy"
requires "gltf"
requires "shady"
requires "opengl"
requires "jsony"
requires "mummy"
requires "crunchy"
requires "curly"
requires "zippy"
requires "yaml >= 2.2.1"
requires "noisy"
requires "fluffy"
requires "benchy"
requires "flatty"
requires "metal4"
